databases:
  - name: krupadb
    plan: free
    databaseName: krupa
    user: krupa

services:
  - type: web
    plan: free
    name: krupa
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn krupa.asgi:application -k uvicorn.workers.UvicornWorker"    
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: krupadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4