# Generated by Django 5.1 on 2024-11-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_delete_estimates'),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='password',
            field=models.CharField(default=True, max_length=30),
            preserve_default=False,
        ),
    ]
