# Generated by Django 5.1 on 2024-11-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0040_alter_bill_vendor_name_alter_purchase_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expense_account', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_through', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sac', models.CharField(blank=True, max_length=50, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_treatment', models.CharField(blank=True, max_length=255, null=True)),
                ('source_of_supply', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_of_supply', models.CharField(blank=True, max_length=255, null=True)),
                ('reverse_charge', models.BooleanField(blank=True, default=False, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, default='Select or add customer', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('expense_account', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_through', models.CharField(blank=True, max_length=255, null=True)),
                ('expense_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expense_type', models.CharField(blank=True, max_length=255, null=True)),
                ('sac', models.CharField(blank=True, max_length=50, null=True)),
                ('gst_treatment', models.CharField(blank=True, max_length=255, null=True)),
                ('source_of_supply', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_of_supply', models.CharField(blank=True, max_length=255, null=True)),
                ('reverse_charge', models.BooleanField(default=False)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, default='Select or add customer', max_length=255, null=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='krupa.vendor')),
            ],
        ),
    ]
