# Generated by Django 5.1 on 2024-11-16 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0042_orders_estimate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorder',
            old_name='satus',
            new_name='status',
        ),
    ]
