# Generated by Django 5.1 on 2024-11-16 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0045_rename_estimate_date_estimate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='estimate',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='krupa.estimate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estimate',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estimate_requests', to='krupa.request'),
        ),
    ]
