# Generated by Django 5.1 on 2024-11-16 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0046_request_estimate_alter_estimate_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='estimate',
        ),
        migrations.AlterField(
            model_name='estimate',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='krupa.request'),
        ),
    ]
