# Generated by Django 5.1 on 2024-11-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0051_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='progress',
            field=models.CharField(blank=True, default='OPEN', max_length=20, null=True),
        ),
    ]
