# Generated by Django 5.1 on 2024-11-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0052_supportticket_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gstin',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
