# Generated by Django 5.1 on 2024-11-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0053_customuser_manager_alter_customuser_gstin'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceestimate',
            name='attachement',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
