# Generated by Django 5.1 on 2024-11-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0054_invoiceestimate_attachement'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='requestid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
