# Generated by Django 5.1 on 2024-11-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0055_request_requestid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='requestid',
        ),
    ]
