# Generated by Django 5.1 on 2024-11-25 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0057_request_requestid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='product_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='krupa.products'),
        ),
    ]
