# Generated by Django 5.1 on 2024-11-26 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0058_alter_request_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('address_type', models.TextField(blank=True, null=True)),
                ('street_address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='krupa.request')),
            ],
        ),
    ]
