# Generated by Django 5.1 on 2024-11-26 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0062_alter_shippingaddress_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
