# Generated by Django 5.1 on 2024-11-26 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krupa', '0063_alter_shippingaddress_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='krupa.shippingaddress'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
